import type { Metadata } from "next";
import "./globals.css";
import { VisualEditing } from 'next-sanity/visual-editing'


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
        {(
          <VisualEditing 
            zIndex={99999}
          />
        )}
      </body>
    </html>
  )
}